services:
  influxdb:
    image: influxdb:1.7.7-alpine
    ports:
        - "127.0.0.1:8086:8086"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
  grafana:
    image: grafana/grafana:7.5.11
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/ruuvi
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ${PWD}/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ${PWD}/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/grafana-dashboard-ruuvioverview.json:/var/lib/grafana/dashboards/ruuvioverview.json
      - ${PWD}/grafana-dashboard-ruuvisensor.json:/var/lib/grafana/dashboards/ruuvisensor.json
    ports:
        - "127.0.0.1:3000:3000"
    depends_on:
      - influxdb
  mqtt:
    image: eclipse-mosquitto:2.0-openssl
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
       - "127.0.0.1:1883:1883"
